### ISSUE TITLE
No module named network

### ISSUE THREAD

**Issue by GaryQi0329** [phenom-films/dayu_ffmpeg#3]
# Net模块问题
通过pip install dayu_ffmpeg 命令行安装了0.5版本的dayu_ffmpeg，在测试时系统提示没有叫做network的模块，报错信息粘贴如下:
Traceback (most recent call last):
> File "/Users/peacockblue_dit/Documents/CodingProjects/LaLaLand/Test.py", line 1, in <module>
    from dayu_ffmpeg import  *
  File "/Users/peacockblue_dit/Documents/CodingProjects/LaLaLand/venv/lib/python2.7/site-packages/dayu_ffmpeg/__init__.py", line 7, in <module>
    from network import *
ImportError: No module named network

**Comment by zyjc007** [comment]
you can install this module by
pip3 install network

**Comment by phenom-films** [comment]
this is caused by missing packages in setup.py.
now fixed.
